module.exports = {
   CreateDepartment:"/department/create",
   CreateDepartmentAndLevels:"/department/levels/create",
   CreateLevel:"/level/create",
   CreateCourse:"/course/create",
   SearchCourse:"/search/course/:searchQuery",
   CreateUser:"/auth/register",
   CreateMaterial:"/material/create",
   CreateComment:"/comment/",
   CreateTimeTableByLevel:"/timetable/",
   FetchUserAllUser:"/users",
   FetchUserByLevel:"/users/:level",
   FetchUserById:"/auth/:userId",
   FetchAllDepartment:"/department/",
   FetchDepartmentWebView:"/department/view",
   FetchCoursesWebView:"/courses/view",
   FetchLevelByDepartmentId :"/:departmentId/level/",
   FetchLevel :"/levels/",
   FetchCourseByLevel:"/:level/course/",
   FetchMaterialsByCourseId:"/material/:courseId",
   FetchMaterials:"/material",
   FetchMaterialsByDepartmentAndLevel:"/material/:department/:level",
   FetchAllBlogs:'/blog/',
   FetchCommentByBlogId:'/comment/:blogId',
   FetchTimeTableByLevel:"/timetable/:level",
   FetchTimeTableByLevelWeb:"/activity/timetable/view/:level",
   DeleteDepartment:"/department/",
   DeleteById:"/auth/:userId",
   DeleteBlog:"/blog/:blogId",
   deleteCommentById:'/comment/:blogId',
   Login :"/auth/login",
   VerifyToken:'/auth/token',
   FetchAllCourse:'/courses/',
   CreateBlog:'/blog/',
   CreateAttendance:'/attendance/',
   CreateAttendanceBulk:'/attendance/bulk',
   FetchAttendance:'/attendance/',
   FetchAttendanceByCourse:'/attendance/:course',
   FetchAttendanceByMatricNumber:'/attendance/matric',
   searchMaterials:"/search/material/:searchQuery",
   filterMaterial:"/filter/material/:query",
   LikeBlogPost:'/blog/like/:blog',
   DisLikeBlogPost:'/blog/dislike/:blog',
   WeaklyActivity:'/activity/week/:level',
   DayActivity:'/activity/day/:level',
   ChangePassword :"/auth/changePassword"
}
